[preset."Wrapper Offline 2.1+"]
resolution = "1280x720"
format = "mp4"
url = "http://127.0.0.1:4343/"
api_url = "http://127.0.0.1:4343/"
swf_url = "http://127.0.0.1:4664/animation/414827163ad4eb60/player.swf"
store_path = "http://127.0.0.1:4664/store/3a981f5cb2739137/<store>"
client_theme_path = "http://127.0.0.1:4664/static/ad44370a650793d9/<client_theme>"
no_outro = false

[preset."Wrapper Offline 2.1+".browser_picker]
start_url = "http://127.0.0.1:4343/"
video_url_regex = '^http://127\.0\.0\.1:4343/\?redirect=/movies/play/(?P<id>[A-Za-z0-9_-]+)(?:[&#].*)?$'

[preset."Wrapper Offline 2.0 and earlier"]
resolution = "1280x720"
format = "mp4"
url = "http://127.0.0.1:4343/"
api_url = "http://127.0.0.1:4343/"
swf_url = "http://127.0.0.1:4343/animation/414827163ad4eb60/player.swf"
store_path = "http://127.0.0.1:4343/store/3a981f5cb2739137/<store>"
client_theme_path = "http://127.0.0.1:4343/static/ad44370a650793d9/<client_theme>"
no_outro = false

[preset."Wrapper Offline 2.0 and earlier".browser_picker]
start_url = "http://127.0.0.1:4343/"
video_url_regex = '^http://127\.0\.0\.1:4343/player\?movieId=(?P<id>[A-Za-z0-9_-]+)(?:[&#].*)?$'

[preset.FlashThemes]
resolution = "1280x720"
format = "mp4"
url = "https://flashthemes.net/"
api_url = "https://flashthemes.net/"
swf_url = "https://lightspeed.flashthemes.net/static/animation/new87/player.swf?v=2"
store_path = "https://lightspeed.flashthemes.net/static/store/<store>?v={user_id}"
client_theme_path = "https://lightspeed.flashthemes.net/static/ct/ad44370a650793d9/<client_theme>"
no_outro = false

[preset.FlashThemes.replacements]
owner_id = "{user_id}"

[preset.FlashThemes.browser_picker]
start_url = "https://flashthemes.net/"
video_url_regex = '^https://(?:www\.)?flashthemes\.net/movie/(?P<id>[A-Za-z0-9_-]+)/?(?:[?#].*)?$'
user_url_regex = '^https://(?:www\.)?flashthemes\.net/user/(?P<id>[0-9]+)/?(?:[?#].*)?$'
